name: wakeonlan
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  connectivity_plus: ^4.0.2
  convert: ^3.1.1
  dynamic_color: ^1.6.2
  flutter:
    sdk: flutter
  lan_scanner: ^4.0.0+1
  network_info_plus: ^4.0.2
  path_provider: ^2.0.13
  provider: ^6.0.5
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
